language: go

go:
  - 1.9
  - 1.10.x

before_install:
  - go get github.com/mattn/goveralls
  - git clone https://github.com/jmcnamara/libxlsxwriter.git && cd libxlsxwriter && make && sudo INSTALL_DIR=/usr make install && cd .. && rm -rf libxlsxwriter

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore "examples/*/*.go" -v
